import type { Metadata } from "next";
import { Geologica } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { Bounce, ToastContainer } from "react-toastify";

import { TRPCProvider } from "@/trpc/client";
import { cn } from "@/lib/utils";

import "./globals.css";

const geologica = Geologica({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased", geologica.className)}>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss={false}
          draggable
          pauseOnHover={false}
          theme="dark"
          transition={Bounce}
        />
        <NextTopLoader />
        <TRPCProvider>{children}</TRPCProvider>
      </body>
    </html>
  );
}
